name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: "Build & test with Maven"
        run: mvn -B test

      # ✅ Upload raw JUnit test results (so you can download them later)
      - name: Upload JUnit results
        if: always()  # Run this even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: target/surefire-reports/

      # ✅ Show pass/fail summary of tests in the GitHub UI
      - name: Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/TEST-*.xml"

        

