name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'

      - name: Build & test with Maven
        run: mvn -B test

      - name: Show Test Summary
        if: always()
        uses: test-summary/action@v2
        with:
          paths: "target/surefire-reports/TEST-*.xml"
          show-failure-details: true         # shows error message of failing tests
          include-passed: true               # shows passed tests
          include-skipped: true              # shows skipped tests

        

